spring:
  application:
    name: kai-dubbo-consumer1

server:
  port: 7071

hello:
  service:
    version: 1.0.0

dubbo:
  application:
    id: kai-dubbo-consumer-id1
    name: kai-dubbo-consumer-name1
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183
    id: kai-registry-1

management:
  endpoint:
    dubbo-configs:
      enabled: true
    dubbo:
      enabled: true
    dubbo-services:
      enabled: true
    dubbo-properties:
      enabled: true
    dubbo-shutdown:
      enabled: true
    dubbo-references:
      enabled: true
  health:
    dubbo:
      status:
        defaults: memory
          extras: load,threadpool
  endpoints:
    web:
      exposure:
        include: '*'
